galaxy_info:
  author: Ioannis Mosutakis
  description: Installs Nginx and configures a minimal test webserver
  company: ACME Corp
  license: Apache-2.0
  role_name: webserver

  min_ansible_version: "2.1"

  platforms:
  - name: EL
    versions:
      - 9

  galaxy_tags:
    - nginx
    - webserver
    - development
    - test

dependencies: []