---
# tasks file for webserver
- name: Update and upgrade yum
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: "Install Nginx to version {{ nginx_version }}"
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Enable Nginx service
  ansible.builtin.service:
    name: nginx
    enabled: yes

- name: Start Nginx service
  ansible.builtin.service:
    name: nginx
    state: started

- name: Copy the Nginx configuration file to the host
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Create link to the new config to enable it
  file:
    dest: /etc/nginx/conf.d/default.conf
    src: /etc/nginx/conf.d/default.conf
    state: link

- name: Create Nginx directory
  ansible.builtin.file:
    path: "{{ nginx_custom_directory }}"
    state: directory

- name: Copy index.html to the Nginx directory
  copy:
    src: files/index.html
    dest: "{{ nginx_custom_directory }}/index.html"
  notify: Restart the Nginx service